// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppdpjdfbipkbpiyrdrws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZHBqZGZiaXBrYnBpeXJkcndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODc0MjUsImV4cCI6MjA2MzY2MzQyNX0.UQN8JVOQtpLhn4y1I6sFhW-T_XLOsOEvfmrmwJvi1r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);